Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/Debugger:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Style/YodaCondition:
  Enabled: false
